
        <!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ClsUsers
* GENERATION DATE:  2014-11-28
* CLASS FILE:        C:\xampp\htdocs\entity-gen\includes/../generated_classes/ClsUsers.php
* FOR MYSQL TABLE:  t_users
* FOR MYSQL DB:     mydentcart
* -------------------------------------------------------
* CODE GENERATED BY:
* PHP-PDO CLASS GENERATOR
* from: >>Kunal Khaware , Computer Enthusiast
* email: >>nandkunal@gmail.com
* skype: >>kunal.nand
* -------------------------------------------------------
*
*/

// **********************
// CLASS DECLARATION
// **********************
require_once(dirname(__FILE__).'/../common/projectConstant.php');
require_once(dirname(__FILE__).'/../exceptions/NoRecordFoundException.php');
class ClsUsers
{ // class : begin

        // **********************
// CONSTRUCTOR DECLARATION
// ********************** 
   public function __construct(){
	 
 }// **********************
// ATTRIBUTE DECLARATION
// **********************
private $ID;//KEY ATTR. WITH AUTOINCREMENT
private $USERNAME;
private $PASSWORD;
private $REGISTRATION_ID;
// **********************
// SETTERS
// **********************
public function setID($val)
{
$this->ID = $val;
}
public function setUSERNAME($val)
{
$this->USERNAME = $val;
}
public function setPASSWORD($val)
{
$this->PASSWORD = $val;
}
public function setREGISTRATION_ID($val)
{
$this->REGISTRATION_ID = $val;
}
// **********************
// GETTERS
// **********************
public function getID()
{
return $this->ID;
}
public function getUSERNAME()
{
return $this->USERNAME;
}
public function getPASSWORD()
{
return $this->PASSWORD;
}
public function getREGISTRATION_ID()
{
return $this->REGISTRATION_ID;
}
// **********************
// INSERT
// **********************
public function save()
{
try
        {
            $dbh = new PDO(DB_DSN, DB_LOGIN, DB_PASSWORD);

        }
        catch (PDOException $e) {
            print "Error!: " .$e->getMessage() . "<br/>";
            die();
        }
$null=NULL;
$stmt=$dbh->prepare("insert into t_users values(?,?,?,?)"); 
$stmt->bindParam(1,$null);
$stmt->bindParam(2,$this->USERNAME);
$stmt->bindParam(3,$this->PASSWORD);
$stmt->bindParam(4,$this->REGISTRATION_ID);
$stmt->execute();
if($stmt->rowCount()>0){
$this->ID=$dbh->lastInsertId();
$is_added=true;
}else{
$is_added=false;
}
$dbh=null;
return $is_added;
}
// **********************
// GET
// **********************
public function get()
{
try
        {
            $dbh = new PDO(DB_DSN, DB_LOGIN, DB_PASSWORD);

        }
        catch (PDOException $e) {
            print "Error!: " .$e->getMessage() . "<br/>";
            die();
        }
$stmt=$dbh->prepare("select * from  t_users where ID = ?"); 
$stmt->bindParam(1,$this->ID);
$stmt->execute();
$row=$stmt->fetch(PDO::FETCH_ASSOC);
if(count($row) == 0){
throw new NoRecordFoundException("No Records Found",100);
}
foreach ($row as $key=>$value)
{
$this->$key=$value;
}
$dbh=null;
}
// **********************
// update
// **********************
public function update()
{
try
        {
            $dbh = new PDO(DB_DSN, DB_LOGIN, DB_PASSWORD);

        }
        catch (PDOException $e) {
            print "Error!: " .$e->getMessage() . "<br/>";
            die();
        }
$null=NULL;
$stmt=$dbh->prepare("update t_users SET USERNAME=?,
PASSWORD=?,
REGISTRATION_ID=?
 WHERE ID=?
");
$stmt->bindParam(1,$this->USERNAME);
$stmt->bindParam(2,$this->PASSWORD);
$stmt->bindParam(3,$this->REGISTRATION_ID);
$stmt->bindParam(4,$this->ID);
$stmt->execute();
if($stmt->rowCount()>0){
$is_modified=true;
}else{
$is_modified=false;
}
$dbh=null;
return $is_modified;
}
// **********************
// delete
// **********************
public function delete()
{
try
        {
            $dbh = new PDO(DB_DSN, DB_LOGIN, DB_PASSWORD);

        }
        catch (PDOException $e) {
            print "Error!: " .$e->getMessage() . "<br/>";
            die();
        }
$stmt=$dbh->prepare("delete from  t_users where ID = ?"); 
$stmt->bindParam(1,$this->ID);
$stmt->execute();
if($stmt->rowCount()>0){
$is_deleted=true;
}else{
$is_deleted=false;
}
$dbh=null;
return $is_deleted;
}

// **********************
// JOIN
// **********************
public function getRegistration()
{
try
        {
            $dbh = new PDO(DB_DSN, DB_LOGIN, DB_PASSWORD);

        }
        catch (PDOException $e) {
            print "Error!: " .$e->getMessage() . "<br/>";
            die();
        }
$stmt=$dbh->prepare("select r.* from t_registration r,t_users u where r.id= ? and u.registration_id=r.id"); 
$stmt->bindParam(1,$this->REGISTRATION_ID);
$stmt->execute();
$row=$stmt->fetch(PDO::FETCH_ASSOC);
if(count($row) == 0){
throw new NoRecordFoundException("No Records Found",100);
}
foreach ($row as $key=>$value)
{
$data[$key]=$value;
}
$dbh=null;
return $data;
}
 
 }
       // end of generated class